module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    EMPLOYEE_ADD_NEW: "EMPLOYEE_ADD_NEW",
    EMPLOYEE_EDIT: "EMPLOYEE_EDIT",
    ADD_ZONE_DETAILS: "ADD_ZONE_DETAILS",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
    EMPLOYEE_DELETE: "EMPLOYEE_DELETE",
    ZONE_DETAILS_DELETE: "ZONE_DETAILS_DELETE",
  },
});
